### ISSUE TITLE
Test running pc_align on CTX/HiRISE images iteratively

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/mars2020_trn#3]
As a user, I would like to understand if pc_align can be successfully used to better align/register CTX and/or HiRISE DTMs to one another so that the offset between DTMs generated separately is minimized in a consistent manner.

I would like a test of running pc_align on CTX images interatively using a more constrained maximum displacement, to see if this produces a well-registered CTX mosaic that matches well to MOLA.  Jezero is the site I would like tested, as that is the DTM mosaic due in March.

**Comment by dpmayerUSGS** [comment]
I have selected 4 overlapping CTX stereopairs over Jezero and will process them into DTMs using ASP
